### ISSUE TITLE
Add thumbnail regenerate button admin-wide

### ISSUE THREAD

**Issue by cristianobaptista** [ponticlaro/bebop-media#4]
### Spec
- Small and versatile button that regenerate all thumbnails (or only the ones that need to be generated) for a single image when clicked
- Button should reflect the state of the image using colours:
  - Red = There are no thumbnails
  - Orange = Some thumbnails are missing and/or do not match its image preset
  - Green = All image sizes that can be generated are in place
- Use simple icons to represent regeneration success, failure and loading status
- Should have at least two layouts:
  - Compact: just a square with an icon
  - Medium: the square with an icon + status message

### Implementation

- [ ] Add a filter dropdown to filter images based on their thumbnail status
- [ ] Add button to [Media Library Grid View](https://codex.wordpress.org/Media_Library_Screen#Media_Library_Grid_View) items
- [ ] Add button to Media Library Grid View, when displaying a single item
- [ ] Add column with button to [Media Library List View](https://codex.wordpress.org/Media_Library_Screen#Media_Library_List_View) items
- [ ] Add button to Media Library List View, when displaying a single item
- [ ] Add button to Bebop UI Media widgets
- [ ] Add button to default **Featured Image** metabox

### Optional implementation
- [ ] Add an HTTP API resource that only regenerate what is needed: `/:id/regenerate-auto` or  `/:id/regenerate/auto`
- [ ] Add admin option to select if the button should regenerate all images OR only the ones that are missing or do not currently match the image size preset

**Comment by huntercross** [comment]
My feeling is that this is an important feature, but ---

I think we can do less possibly and take care of more of our customer's problems.

The use case we run into more than anything, is the use case where a site wants to regenerate ALL images that have been uploaded so far, because something changes on the frontend. Meaning - some new standard image was asked for by the design.  In this case, the user would have to go through ALL images to update them with the button, which would be really unwieldy for a large media library.

**Comment by huntercross** [comment]
So - given that, what sort of Single button push on Mission Control that would start the regeneration of the images on AWS and then it sends an email to team@ponticlaro.com and the client when that regeneration is over.

**Comment by huntercross** [comment]
I am not sure if that is possible to run as a background process, i believe it is, possibly with a worker queue...but let me know if we have that option, given the potential for 1,000 or 10,000 images...I wouldn't want to imagine 100,000 but i guess we should probably test that at some point.

**Comment by cristianobaptista** [comment]
Instead of this, lets go with #5
