### ISSUE TITLE
Use image_downsize hook to provide on the fly image size generation

### ISSUE THREAD

**Issue by cristianobaptista** [ponticlaro/bebop-media#6]
https://developer.wordpress.org/reference/functions/image_downsize/

Notes:
- This function won’t create a new resized copy, it will just return an already resized one if it exists
- A plugin may use the ‘image_downsize’ filter to hook into and offer image resizing services for images

@huntercross

**Comment by huntercross** [comment]
The built-in generation of wordpress I think should be avoided.

**Comment by cristianobaptista** [comment]
I was not thinking about the built-in thumbnail generation WordPress have. I was thinking this would be the hook to do anything about thumbnail generation on the fly, if we ever wanted to.
